# Generated by Django 5.0.2 on 2024-02-26 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0004_book_fk_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('Classics', 'Classics'), ('Commic Book', 'Comic Book'), ('Fantasy', 'Fantasy'), ('Horror', 'Horror'), ('Programming', 'Programming')], max_length=200, null=True),
        ),
    ]
